event/urls.py
from django.conf.urls.defaults import *
from event.views import *
from django.conf import settings
urlpatterns = patterns('event.views',
    url(r'this_event/(\d+)/$', 'event_detail', name = 'event_detail'),
    url(r'create_event/$', 'event_create', name = 'event_create'),
    url(r'event/', 'events_list', name = 'events_list'),
    
    
    
)

urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from ssp.views import main_page
from django.contrib.auth.decorators import login_required

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('ssp.views',
	url(r'about/','about_page',name='about_page'),
	url(r'graduated/','graduated',name='graduated'),
	url(r'^$','main_page',name='main_page'),
	url(r'account/',include("reg.urls")),
	url(r'discussion/',include("discussion.urls")),
	url(r'files/',include("files.urls")),
	url(r'events/',include("event.urls")),
	url(r'anketa/',include("anketa.urls")),
    # Example:
    # (r'^ssp/', include('ssp.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
	(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
	(r'^admin/', include(admin.site.urls)),
)
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True} ),
    )

event/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

# Create your models here.
class Event(models.Model):
    author=models.ForeignKey(User)
    title=models.CharField(max_length=50)
    description=models.TextField()
    date=models.DateField()
    start_time=models.TimeField()
    def __unicode__(self):
        return self.title
    
class CommentEvent(models.Model):
    author=models.ForeignKey(User)
    event=models.ForeignKey(Event)
    comment=models.TextField()
    created_date=models.DateField(auto_now_add=True) 
    def __unicode__(self):
        return self.comment   

event/forms.py
from django import forms
from event.models import *
from event.forms import *

class EventForm(forms.ModelForm):
    class Meta:
        model=Event
        exclude=('author')
class EventCommentForm(forms.ModelForm):
    class Meta:
        model=CommentEvent
        exclude=('event','author')
        

event/views.py
from event.models import *
from event.forms import *

from django.shortcuts import render_to_response 
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

@login_required
def events_list(request):
    events=Event.objects.all()
    rc=RequestContext(request,{'events':events})
    return render_to_response("events/events_list.html",rc)
@login_required
def event_detail(request,event_id):
    event=Event.objects.get(id=event_id)
    com= CommentEvent(event=event,author=request.user)
    print com
    if request.method=="POST":
        ce= EventCommentForm(request.POST,instance=com)
        if ce.is_valid():
            ce.save()
            return HttpResponseRedirect(reverse('event_detail',args=(event_id,)))
    else:
        ce= EventCommentForm(instance=com)
        print ce
    rc=RequestContext(request,{'cform':ce,'event':event})
    return render_to_response("events/event_detail.html",rc)
@login_required
def event_create(request):
    event=Event(author=request.user)
    if request.method=="POST":
        eform=EventForm(request.POST,instance=event)    
        if eform.is_valid():
            eform.save()
            return HttpResponseRedirect(reverse('event_detail',args=(event.id,)))
    else:
        eform=EventForm(instance=event)
    rc=RequestContext(request,{'eform':eform})
    return render_to_response("events/event_create.html",rc)
         

templates/events/event_create.html
{%extends "index.html"%}
{%block content%}

<h2>Create Event</h2>
<form action="" method="post">{%csrf_token%}
{{eform.as_p}}		

<script>
$(function() {
$( "#id_date" ).datepicker();
});
</script>
		<input type='submit' value='create' />
	</form>
{%endblock%}

templates/events/event_detail.html
{%extends "index.html"%}
{%block content%}

<h2>{{event.title}}</h2>
<h3>{{event.description|safe}}</h3>
<p><b>Date:</b></p><p>{{event.date}}</p>
<p><b>Time start:</b></p><p>{{event.start_time}}</p>

{%for c in event.commentevent_set.all%}
<ul>
<p>Commented by <b>{{c.author}}</b> : {{c}}</p>

</ul>
{%endfor%}

<form action="" method="post">{%csrf_token%}
		<table>
{{cform.as_p}}
</table>
		<input type='submit' value='post' />
	</form>
{%endblock%}

templates/events/events_list.html
{%extends "index.html"%}
{%block content%}
{%for e in events%}
<table>
<tr>
<td>
<a href="{%url event_detail e.id%}">{{e}}</a>
</td>
</tr>
</table>
{%endfor%}
<a href="{%url event_create%}">Create Events</a>
{%endblock%}